45 mega cooles refactoring hoert dafür die zweite sprachnachricht
ReTtiChDieOrganisation/ReTtiChDasRepo pull request #87
Opened 2023-10-18 21:51 UTC by FelixTe

Soooo guckt es euch mal an

2023-10-18 21:52 UTC, FelixTe commented
wers nohc wach @Flo1314

2023-10-18 21:58 UTC, FelixTe commented
Ich verstehe leider auch noch nicht wie man den conflict resolved

2023-10-19 14:43 UTC, FelixTe commented
Soo hab den pull request mal reopend @prosauer @jac803 @Flo1314

2023-10-19 14:44 UTC, FelixTe reviewed
Also da haben wir uns mal wieder selbst übertroffen. Es sieht so gut aus

2023-10-19 19:01 UTC, prosauer requested changes
Sehr cool!!

2023-10-19 19:03 UTC, prosauer commented on index.html
>  						current_segment = $("#sel").val().split(',')
```suggestion
						current_segment = $("#sel"_segment).val().split(',')
```

2023-10-19 20:01 UTC, prosauer approved these changes
🥳

2023-10-19 20:46 UTC, Flo1314 reviewed
lgtm, habs nicht ausgecheckt und ausprobiert haha

2023-10-19 20:46 UTC, Flo1314 commented on frontend/data/rettich/icons.js
> +    /* TODO:
oh ja, hab vergessen die Kommentare zu löschen

2023-10-19 21:37 UTC, merged

2023-10-19 21:47 UTC, FelixTe commented
Ich muss mir die Reviews mal genauer angucken auf dem Handy ist das nichts habe auch eben einfach nur blind angenommen